source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '2.6.3'

gem 'jwt', '1.5.6'
gem 'pg', '0.21.0'
gem 'puma', '4.3.8'
gem 'rack-cors', '0.4.1'
gem 'rails', '5.2.3'

group :development, :test do
  gem 'factory_girl_rails', '4.9.0'
  gem 'rspec-rails', '3.8.2'
  gem 'sqlite3', '1.4.1'
end

group :development do
  gem 'listen', '3.1.5'
  gem 'spring', '2.0.2'
  gem 'spring-watcher-listen', '2.0.1'
end
